### ISSUE TITLE
Why are only half the possible machine IDs and sequence numbers used?

### ISSUE THREAD

**Issue by hi2u** [sschiau/Particle#7]
I might be misunderstanding something really basic here.  But according to README.md...

> configured machine id - 10 bits - up to 512 machines
> sequence number - 12 bits - up to 2048 random numbers

Why are only half of the values available for each of these? i.e....

- 10 bits allows 1024 values, so why only up to 512 machines?  
- 12 bits allows 4096 values, so why only up to 2048 random numbers for sequence?

**Comment by sschiau** [comment]
> The number 9,223,372,036,854,775,807, equivalent to the hexadecimal value 7FFF,FFFF,FFFF,FFFF16, is the maximum value for a 64-bit signed integer in computing.
https://en.wikipedia.org/wiki/9223372036854775807

This is 2^63-1 (That's 64bit max value).
Particle always creates a 64bit number. Therefor, the range is 2^62 till 2^63-1.
It will not create a number in the 63 bit space to in the 65 bit space.

To have a consistent 64bit number, I'm only allowing in machineId the values that are in the range of min/max for 10 bits (512 values). Seq. no is the same.

**Comment by hi2u** [comment]
41+10+12 bits = 63 bits

All the other similar generators use all the bits, one other example in PHP:  https://webartisan.se/generating-globally-unique-time-sortable-ids-php/  

I think you're confusing the overall number of bits (63, to fit in an unsigned bigint) with the number of bits in each element making up the total.  

10 bits of machine ID can go from 0 up to:
1111111111 = 1023

12 bits of random can go from 0 up to:
111111111111 = 4059 

So as long as your timestamp remains 41 bits, you're still always going to have exactly 63 bits in the end.  So it's never going to go above 9223372036854775807.

Anyway, up to you, but you're wasting 2 bits.

**Comment by sschiau** [comment]
Thanks for the input.

Improved in https://github.com/sschiau/Particle/commit/4570e1491a00f6943b8608045d042dd9b4a504a8 as part of v2.0.0
